blank_issues_enabled: false
contact_links:
  - name: 📖 README
    url: https://github.com/tokamak-network/dao-agenda-metadata-repository/blob/main/README.md
    about: Project overview and getting started information
  - name: 📚 Documentation & Guides
    url: https://github.com/tokamak-network/dao-agenda-metadata-repository/tree/main/docs
    about: Complete documentation, guides, and technical references
