blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation & Guides
    url: https://github.com/tokamak-network/dao-agenda-metadata-repository/tree/main/docs
    about: Metadata registration, validation, and signature creation guides
  - name: 📖 README
    url: https://github.com/tokamak-network/dao-agenda-metadata-repository/blob/main/README.md
    about: Project overview and getting started information
  - name: 🌐 Tokamak Network Official Site
    url: https://tokamak.network
    about: Official Tokamak Network information